name: Build Artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    # - name: Build fat jar with Ant
    #  run: ant -f build.xml ci
    - name: Build jar and dmg with maven
      run: mvn clean package
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GobangGame-JAR
        path: target/GobangGame.jar
        retention-days: 7
    - name: Upload Source JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GobangGame-SRC-JAR
        path: target/GobangGame-sources.jar
        retention-days: 7
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GobangGame-DMG
        path: target/*.dmg
        retention-days: 7
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GobangGame-EXE
        path: target/*.exe
        retention-days: 7
    - name: Upload linux executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GobangGame-Linux
        path: target/GobangGame
        retention-days: 7
    # - name: Upload logs as artifact
    #  if: failure()
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: build-logs
    #    path: target/surefire-reports/
    #    retention-days: 7
      